version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install Poetry
      - pip install poetry
      # Configure Poetry to avoid creating its own virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install project dependencies, including the 'docs' group
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py