version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install Poetry
      - pip install poetry
      # Configure Poetry to avoid creating its own virtual environment
      - poetry config virtualenvs.create false
      # Install Sphinx extensions directly to ensure they're available
      - pip install sphinx-autodoc-typehints sphinx-rtd-theme myst-parser
    post_install:
      # Install project dependencies with both dev and docs groups
      - poetry install --with dev,docs

sphinx:
  configuration: docs/source/conf.py